name: Terraform Github

on:
  push:
    paths:
      - 'usecase-2/**'
      - '.github/workflows/terraform.yml'
      
  workflow_dispatch:
  
jobs:
  terrform-uc2:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-2

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: SetUp AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          ami_id          = "ami-0803576f0c0169402"
          vpc_cidr        = "10.0.0.0/16"
          public_subnets  = ["10.0.11.0/24", "10.0.12.0/24"]
          private_subnets = ["10.0.21.0/24", "10.0.22.0/24"]
          azs             = ["eu-west-1a", "eu-west-1b"]
          region          = "eu-west-1"
          vpc_name        = "Custom-VPC"
          db_password     = "${{ secrets.UC2_DB_PASSWORD ))"
          db_engine       = "postgres"
          EOF

      - name: Run implement terraform
        run: |
          terraform init
          terraform fmt
          terraform validate
          terraform plan -var-file=terraform.tfvars
          terraform apply -var-file=terraform.tfvars -auto-approve
