name: Terraform Github Use Case - 10

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action to be performed"
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy
        
  push:
    paths:
      - 'usecase-10/**'
      - .github/workflows/usecase-10.yml'
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-10

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2
        with: 
          ref: ${{ github.head_ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE }}

      - name: Build and push
        if: ${{ github.event.inputs.action != 'destroy' }}
        run: |
          cd hospital
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 427521931204.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t patients .
          docker tag patients:latest 427521931204.dkr.ecr.ap-south-1.amazonaws.com/patients:latest
          docker push 427521931204.dkr.ecr.ap-south-1.amazonaws.com/patients:latest


          docker build -t appointments -f Dockerfile.dev .
          docker tag appointments:latest 427521931204.dkr.ecr.ap-south-1.amazonaws.com/appointments:latest
          docker push 427521931204.dkr.ecr.ap-south-1.amazonaws.com/appointments:latest

  terraform:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-10

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2
        with: 
          ref: ${{ github.head_ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE }}

      - name: Pull terraform.tfvars from S3
        run: |
          aws s3 cp s3://terraform-usecases-batch6/env/usecase-10/terraform.tfvars .

      - name: Initiate terraform
        run: |
          terraform init
          terraform fmt -recursive
          terraform validate

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve
